name: submission_2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  connectivity_plus: ^2.3.5
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.3
  get: 4.6.5
  http: ^0.13.4
  json_annotation: ^4.6.0
  lottie: ^1.3.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.5
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/
